name: Deploy Images

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.changes.outputs.base }}
      qt: ${{ steps.changes.outputs.qt }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2 
        id: changes
        with:
          filters: |
            base:
              - 'base/**'
            qt:
              - 'qt/**'

  deploy-base:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.base == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy
        run: make base && make push-base

  deploy-qt:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.qt == 'true' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy
        run: make qt && make push-qt
